### PR TITLE
Remove python2 compat codes, introduce dataclasses and type hints for `bin/update-tables.py`

### PR DESCRIPTION
**Pull request by GalaxySnail**

### CODE REVIEW

**Comment by jquast** [comment]
Thanks for this work. Can I please turn your attention to the use-jinja branch? It is mostly completed and simplifies this script a great deal by using jinja2 templates. https://github.com/jquast/wcwidth/compare/use-jinja

The jinja2 branch is to start generating C code and improve performance of this library. If you are interested in helping with that effort, I have been looking for a co-maintainer, your work is good, are you interested?

**Comment by GalaxySnail** [comment]
> Thanks for this work. Can I please turn your attention to the use-jinja branch? It is mostly completed and simplifies this script a great deal by using jinja2 templates. https://github.com/jquast/wcwidth/compare/use-jinja

Yes. Templates can be more readable than code generator. I haven't used jinja2 before, so let me read its documents first. 

> The jinja2 branch is to start generating C code and improve performance of this library.

I agree, C code will be good. Which should we use, [Python/C API](https://docs.python.org/3/c-api/index.html) or [Cython](https://cython.readthedocs.io/en/latest/)? Python/C API has some disadvantages (for example, reference counting), and there is a WIP replacement named [hpy](https://hpyproject.org/), which may be better.

> If you are interested in helping with that effort, I have been looking for a co-maintainer, your work is good, are you interested?

It's my pleasure. 😉

**Comment by jnoortheen** [comment]
@jquast you may be interested in [mypyc](https://mypyc.readthedocs.io/en/latest/introduction.html) . It was recently used in black as well.

**Comment by GalaxySnail** [comment]
> you may be interested in [mypyc](https://mypyc.readthedocs.io/en/latest/introduction.html) . It was recently used in black as well.

I think the algorithm will be implimented in C, and either Python/C API or cython is only for wrapping the C code in a Python extension module.

AFAIK, mypyc [doesn't support pypy](https://github.com/python/mypy/issues/8217). At least, it haven't been tested on pypy, and mypy [doesn't distribute any mypyc-compiled wheels for pypy on pypi.org](https://pypi.org/project/mypy/0.941/#files) either (There's only `cp` ABI for cpython). And I doubt that mypyc can provide speed up as much as C code does.

Cython [does support pypy](https://cython.readthedocs.io/en/latest/src/userguide/pypy.html) (via pypy's cpyext). And cython has a [pure python mode](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html) (but I haven't used it before, I'm not sure if we can make both cython and mypy's type checker happy). Futher more, if one day cython supports [HPy backend](https://github.com/cython/cython/pull/4490), we can get more performance improvement on pypy (and graalpython, and some others).

**Pull request closed without merging**
