### PR TITLE
Set targets on badges

### PR DESCRIPTION
**Pull request by msabramo**
so that clicking them goes somewhere useful rather than opening the image in the browser.

Try it out at https://github.com/msabramo/wcwidth/tree/set_targets_on_badges

### CODE REVIEW

**Comment by jquast** [comment]
Does that work for you ? 

I found I had to switch to lower-resolution .png images to make targets work, apparently some kind of lame browser vulnerability

**Comment by jquast** [comment]
I'm probably thinking of pypi, anyway I'll try it, would be nice if it did work.

**Comment by msabramo** [comment]
Yeah, it works for me in Chrome on OS X 10.9.5

**Comment by msabramo** [comment]
PyPI just yesterday completely changed their code used for rendering (so it uses pypa/readme). 

So things that didn't work before might work now (and vice-versa).

**Pull request merged**
